const {chromium}=require('playwright');const fs=require('fs');const out=process.env.QA_DIR||'matrix-qa';fs.mkdirSync(out,{recursive:true});const base=process.env.BASE_URL||'http://localhost:8080';const checks=[],errors=[],requests=[];const check=(name,pass,detail='')=>{checks.push({name,pass:!!pass,detail});if(!pass)console.error('FAIL',name,detail)};
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),headless:true,args:['--no-sandbox']});try{
for(const width of [390,768,1440])for(const lang of ['en','fa'])for(const motion of ['no-preference','reduce']){const p=await b.newPage({viewport:{width,height:1000},reducedMotion:motion});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)requests.push({url:r.url(),status:r.status()})});await p.goto(`${base}/?lang=${lang}&theme=dark`);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(1400);const label=`${width}/${lang}/${motion}`;check('13 original sections / five original projects '+label,await p.locator('main>section').count()===13&&await p.locator('.project-card').count()===5);check('No overflow '+label,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check('Matrix dependencies load '+label,await p.evaluate(()=>!!window.gsap&&!!window.ScrollTrigger&&!!window.Lenis));check('One matrix canvas '+label,await p.locator('#matrix-rain').count()===1);check('Canvas budget '+label,await p.evaluate(()=>{const c=document.querySelector('#matrix-rain');return c.width*c.height<=2001000}));check('Three visual additions '+label,await p.locator('.matrix-cinema').count()===1&&await p.locator('.matrix-story-deck').count()===1&&await p.locator('.matrix-field-panel').count()===1);check('Reduced motion / Lenis policy '+label,await p.evaluate(()=>{const d=MATRIX_FX.getDiagnostics();return d.reduced?(!d.lenis&&document.documentElement.dataset.motion==='off'):true}));
if(motion==='no-preference'){
 await p.locator('#motion-toggle').click();check('Motion off releases effects '+label,await p.evaluate(()=>document.documentElement.dataset.motion==='off'&&!MATRIX_FX.getDiagnostics().lenis&&document.querySelectorAll('#matrix-rain').length===1));await p.locator('#motion-toggle').click();await p.waitForTimeout(500);check('Motion on has one lifecycle '+label,await p.evaluate(()=>document.querySelectorAll('#matrix-rain').length===1&&document.querySelectorAll('.matrix-cinema').length===1));
 await p.locator('.matrix-cinema-actions a').last().click();await p.waitForTimeout(1000);check('Portal retains real anchor '+label,p.url().endsWith('#about'));check('Target section is visible '+label,await p.locator('#about').evaluate(el=>el.getBoundingClientRect().top<180));
 await p.locator('[data-system="safevision"]').scrollIntoViewIfNeeded();await p.locator('[data-system="safevision"]').click();await p.waitForTimeout(950);check('Nested system transition preserves selected content '+label,await p.locator('#system-content h3').innerText()==='DetectSafeVisionX');
 await p.locator('#search-open').click();await p.locator('#search-input').fill('3D Visualizer');check('Animated search still finds project '+label,await p.locator('#search-results a').count()===1);await p.keyboard.press('Escape');check('Animated dialog focus returns '+label,await p.locator('#search-open').evaluate(el=>document.activeElement===el));
 await p.locator('.matrix-field').scrollIntoViewIfNeeded();await p.locator('.matrix-field').focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(80);check('Field keyboard visual response '+label,(await p.locator('.matrix-field-coordinate').innerText()).includes('8'));await p.locator('.matrix-field-reset').click();await p.waitForTimeout(80);check('Field reset '+label,(await p.locator('.matrix-field-coordinate').innerText()).includes('X / 0'));
 await p.locator('#language').click();await p.waitForTimeout(1400);check('Language rerender no duplicate engines '+label,await p.locator('#matrix-rain').count()===1&&await p.locator('.matrix-field').count()===1);}
await p.close()}
// Explicit no-View-Transition and missing-library fallback, with all business handlers intact.
for(const fallback of ['view-transitions','libraries']){const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});p.on('pageerror',e=>errors.push(e.message));if(fallback==='view-transitions')await p.addInitScript(()=>{document.startViewTransition=undefined});else await p.route('**/scripts/vendor/*.js',r=>r.abort());await p.goto(base+'/?lang=en&theme=dark');await p.waitForTimeout(1200);await p.locator('.matrix-cinema-actions a').last().click();await p.waitForTimeout(1000);check('Fallback section navigation '+fallback,p.url().endsWith('#about'));await p.locator('[data-filter="automation"]').click();check('Fallback original filtering '+fallback,await p.locator('.project-card:visible').count()===2);await p.close()}
// Cross-document transition opt-in and shared-element naming on a genuine route.
const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/?lang=en&theme=dark');await p.waitForTimeout(1400);const shared=await p.evaluate(()=>{MATRIX_FX.sharedFor(new URL('/redline/work/telebrief.html',location.href));return document.querySelectorAll('[data-matrix-shared]').length});check('Shared source elements uniquely named',shared===2);await p.locator('.project-card h3 a').first().click();await p.waitForTimeout(1400);check('Case route still loads',await p.locator('.case-hero h1').innerText()==='TeleBrief');check('Case has no home-only additions',await p.locator('.matrix-cinema,.matrix-story-deck,.matrix-field-panel').count()===0);await p.locator('.case-hero>a').first().click();await p.waitForTimeout(1400);check('Back to home project anchor',p.url().endsWith('/#projects'));await p.close();
// Desktop frame cadence is a lab measurement, not a hardware guarantee.
const perf=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});await perf.goto(base+'/?lang=en&theme=dark');await perf.waitForTimeout(1500);const stats=await perf.evaluate(()=>new Promise(resolve=>{const times=[];let last;function step(t){if(last)times.push(t-last);last=t;if(times.length<120)requestAnimationFrame(step);else{const sorted=[...times].sort((a,b)=>a-b);resolve({samples:times.length,median:sorted[Math.floor(times.length*.5)],p95:sorted[Math.floor(times.length*.95)],over34ms:times.filter(t=>t>34).length})}}requestAnimationFrame(step)}));fs.writeFileSync(out+'/frame-cadence.json',JSON.stringify(stats,null,2));check('Frame sample captured',stats.samples===120,stats);
await perf.screenshot({path:out+'/desktop-en-dark.png'});await perf.locator('#process').scrollIntoViewIfNeeded();await perf.waitForTimeout(1000);await perf.screenshot({path:out+'/story-en-dark.png'});await perf.locator('.matrix-field-panel').scrollIntoViewIfNeeded();await perf.waitForTimeout(1000);await perf.screenshot({path:out+'/field-en-dark.png'});await perf.goto(base+'/?lang=fa&theme=light');await perf.waitForTimeout(1400);await perf.screenshot({path:out+'/desktop-fa-light.png'});await perf.setViewportSize({width:390,height:1100});await perf.goto(base+'/?lang=fa&theme=dark');await perf.waitForTimeout(1400);await perf.screenshot({path:out+'/mobile-fa-dark.png'});await perf.locator('.matrix-field-panel').scrollIntoViewIfNeeded();await perf.waitForTimeout(1000);await perf.screenshot({path:out+'/mobile-field-fa.png'});await perf.close();
check('No uncaught JavaScript errors',!errors.length,errors);check('No unplanned HTTP failures',!requests.length,requests);
}catch(e){check('Suite completed',false,e.stack)}finally{await b.close();const report={checks,errors,requests,summary:{passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,total:checks.length}};fs.writeFileSync(out+'/matrix-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));process.exitCode=report.summary.failed?1:0}})();
