/* Dependency-free Chromium DevTools smoke/regression tests. */
import {spawn,execSync} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';
const base=process.env.BASE_URL||'http://127.0.0.1:8081',port=30000+Math.floor(Math.random()*20000);
const browser=spawn(process.env.CHROMIUM_PATH||execSync('command -v chromium',{encoding:'utf8'}).trim(),['--headless','--no-sandbox','--disable-dev-shm-usage',`--remote-debugging-port=${port}`,`--user-data-dir=${fs.mkdtempSync(os.tmpdir()+'/redline-qa-')}`],{stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let ws,report=[],exceptions=[];
const check=(name,pass,detail='')=>{report.push({name,pass:!!pass,detail});if(!pass)console.log('FAIL',name,detail)};
try{
 let info;for(let i=0;i<100;i++){try{info=await(await fetch(`http://127.0.0.1:${port}/json/version`)).json();break}catch{await sleep(100)}}if(!info)throw Error('Chromium did not start');
 ws=new WebSocket(info.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
 let id=0;const waiting=new Map();
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=waiting.get(m.id);waiting.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)};
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const n=++id;const timer=setTimeout(()=>{waiting.delete(n);reject(Error('CDP timeout '+method))},15000);waiting.set(n,{resolve:x=>{clearTimeout(timer);resolve(x)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id:n,method,params,...(sessionId?{sessionId}:{})}))});
 const {targetId}=await send('Target.createTarget',{url:'about:blank'});const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
 const page=(m,p={})=>send(m,p,sessionId);await page('Runtime.enable');await page('Page.enable');await send('Target.activateTarget',{targetId});await page('Emulation.setFocusEmulationEnabled',{enabled:true});
 const run=async expression=>{const r=await page('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
 const click=selector=>run(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const key=async(k,code=k,virtual=0)=>{await page('Input.dispatchKeyEvent',{type:'rawKeyDown',key:k,code,windowsVirtualKeyCode:virtual,nativeVirtualKeyCode:virtual});await page('Input.dispatchKeyEvent',{type:'keyUp',key:k,code,windowsVirtualKeyCode:virtual})};
 const go=async(lang='en',width=1440,theme='dark')=>{await page('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await page('Network.enable');await page('Network.setCacheDisabled',{cacheDisabled:true});await page('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await page('Page.navigate',{url:base+`/?lang=${lang}&theme=${theme}`});for(let n=0;n<100;n++){try{if(await run('!!document.querySelector(".hero h1")&&!!window.PORTFOLIO'))break}catch{}await sleep(50)}await run('Promise.race([document.fonts.ready.then(()=>true),new Promise(r=>setTimeout(()=>r(false),2000))])');await sleep(200)};
 for(const width of [360,390,768,1024,1440,2560])for(const lang of ['en','fa']){
  console.log('Viewport',width,lang);await go(lang,width);
  check(`No horizontal overflow ${width}/${lang}`,await run('document.documentElement.scrollWidth<=innerWidth+1'));
  check(`RTL/LTR ${width}/${lang}`,await run(`document.documentElement.lang==='${lang}'&&document.documentElement.dir==='${lang==='fa'?'rtl':'ltr'}'`));
  check(`Sections ${width}/${lang}`,await run('document.querySelectorAll("main>section").length===7&&document.querySelectorAll(".coming-card").length===4'));
  check(`Reduced motion ${width}/${lang}`,await run('getComputedStyle(document.querySelector(".marquee-track")).animationName==="none"'));
  await click('[data-project=allin1wrench]');check(`Project dialog ${width}/${lang}`,await run('document.querySelector("#project-dialog").open'));
  await run('document.querySelector(".gallery").focus()');await key('ArrowRight','ArrowRight',39);await sleep(50);check(`Gallery keys ${width}/${lang}`,await run('document.querySelector(".gallery").scrollLeft>0'));
  await key('Escape','Escape',27);await sleep(150);check(`Escape & focus ${width}/${lang}`,await run('!document.querySelector("#project-dialog").open&&document.activeElement.matches("[data-project]")'),await run('JSON.stringify({open:document.querySelector("#project-dialog").open,focus:document.activeElement.outerHTML.slice(0,240)})'));
  if(width<801){await click('#menu');check(`Mobile menu ${width}/${lang}`,await run('document.querySelector("#menu").getAttribute("aria-expanded")==="true"'));await key('Escape','Escape',27)}
 }
 await go();
 await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"k",ctrlKey:true,bubbles:true}))');check('Command opens',await run('document.querySelector("#command-dialog").open'));
 await run('(()=>{const x=document.querySelector("#command-input");x.value="TeleBrief";x.dispatchEvent(new Event("input",{bubbles:true}));})()');check('Command search',await run('document.querySelectorAll(".command-item").length===1'));
 await key('Enter','Enter',13);await sleep(100);check('Command opens TeleBrief',await run('document.querySelector("#project-title").textContent==="TeleBrief"'));
 await click('#next-project');await sleep(100);check('Next project',await run('document.querySelector("#project-title").textContent==="BotAM"'));check('Next keeps scroll locked',await run('document.body.style.overflow==="hidden"'));await key('Escape','Escape',27);await sleep(50);
 await run('document.dispatchEvent(new KeyboardEvent("keydown",{key:"k",ctrlKey:true,bubbles:true}))');await run('(()=>{const x=document.querySelector("#command-input");x.value="no-match-zzzz";x.dispatchEvent(new Event("input",{bubbles:true}));})()');check('Command empty state',await run('!!document.querySelector(".command-empty")'));await key('Escape','Escape',27);
 for(const [filter,n] of [['product',2],['study',1],['all',3]]){await click(`[data-filter=${filter}]`);check(`Filter ${filter}`,await run(`Array.from(document.querySelectorAll('.project-card')).filter(x=>!x.hidden).length===${n}`))}
 await click('#theme');check('Theme toggle',await run('document.documentElement.dataset.theme==="light"'));await click('#language');check('Language toggle',await run('document.documentElement.dir==="rtl"'));await click('#language');
 await run('document.querySelector("#email-blog").value="person@example.test";document.querySelector("#blog input[name=consent]").checked=true;document.querySelector("#blog form").requestSubmit()');await sleep(50);check('Unconfigured newsletter is honest',await run('document.querySelector("#blog .form-message").textContent.includes("not connected")'));
 await run('document.querySelector("#contact-name").value="Test";document.querySelector("#contact-email").value="person@example.test";document.querySelector("#contact-message").value="Test only";document.querySelector(".contact-form").requestSubmit()');check('Unconfigured contact is honest',await run('document.querySelector(".contact-form .form-message").textContent.includes("not configured")'));
 await run('window.PORTFOLIO.integrations.newsletterEndpoint="/api/newsletter";window.__fetch=window.fetch;window.fetch=async (url,options)=>{window.__request=JSON.parse(options.body);return new Response("{}",{status:200})};document.querySelector("#blog form").requestSubmit()');await sleep(100);check('Newsletter POST payload',await run('window.__request.email==="person@example.test"&&window.__request.section==="blog"&&window.__request.consent===true'));check('Mock provider accepted',await run('document.querySelector("#blog .form-message").textContent.includes("accepted")'));
 await run('window.fetch=async()=>new Response("error",{status:500});document.querySelector("#email-blog").value="person@example.test";document.querySelector("#blog input[name=consent]").checked=true;document.querySelector("#blog form").requestSubmit()');await sleep(100);check('Provider error preserves input',await run('document.querySelector("#blog .form-message").textContent.includes("Could not send")&&document.querySelector("#email-blog").value==="person@example.test"'));await run('window.fetch=window.__fetch');
 await run('window.PORTFOLIO.sections.find(x=>x.id==="blog").launchAt="invalid";window.PORTFOLIO.sections.find(x=>x.id==="blog").illustrativeDate=false');await click('#theme');check('Invalid date safe',await run('document.querySelector("#blog .countdown").textContent.includes("Launch date")'));
 await run('window.PORTFOLIO.sections.find(x=>x.id==="blog").launchAt="2020-01-01T00:00:00Z"');await click('#theme');check('Expired countdown safe',await run('document.querySelector("#blog .countdown").textContent.includes("Target reached")'));
 await run('window.PORTFOLIO.sections.push({id:"new-section",type:"content",nav:{en:"New",fa:"جدید"},title:{en:"New section",fa:"بخش جدید"},body:{en:"Data only",fa:"داده"}})');await click('#theme');check('Data-driven new section',await run('!!document.querySelector("#new-section")'));
 await run('document.querySelector(".project-cover img").dispatchEvent(new Event("error"))');check('Image failure fallback',await run('!!document.querySelector(".project-cover .image-failed")'));
 await go('en',1440,'dark');check('No missing asset references',await run('performance.getEntriesByType("resource").every(x=>!x.name.includes("/assets/fonts/")&&!x.name.includes("/assets/images/"))'));
 await page('Emulation.setScriptExecutionDisabled',{value:true});await page('Page.navigate',{url:base});await sleep(400);check('No-JS fallback',await run('!!document.querySelector("noscript h1")'));await page('Emulation.setScriptExecutionDisabled',{value:false});
 check('No runtime exceptions',exceptions.length===0,exceptions.join('; '));
}finally{ws?.close();browser.kill()}
const result={date:new Date().toISOString(),environment:'Headless Chromium / Linux, dependency-free CDP; GitHub-exact text asset bundle',passed:report.filter(x=>x.pass).length,total:report.length,checks:report,notMeasured:['Lighthouse','Full WCAG conformance','Physical-device FPS','Live email delivery','Safari / Firefox']};fs.writeFileSync(new URL('../QA-results.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,total:result.total,failed:report.filter(x=>!x.pass)},null,2));if(result.passed!==result.total)process.exitCode=1;
