(() => {
'use strict';
const {$,$$,esc:e,text:x,t}=R,C=window.REDLINE_CONTENT,P=window.REDLINE_PROJECTS;
const nav=[['projects','work'],['about','about'],['systems','systems'],['lab','lab'],['contact','contact']];
function controls(){const theme=$('#theme'),motion=$('#motion-toggle');if(theme){theme.setAttribute('aria-label',t('theme'));theme.setAttribute('aria-pressed',String(R.state.theme==='dark'));theme.innerHTML=`<span aria-hidden="true">${R.state.theme==='dark'?'☼':'◐'}</span>`}if(motion){motion.setAttribute('aria-label',t('motion'));motion.setAttribute('aria-pressed',String(R.state.motion));motion.innerHTML=`<span aria-hidden="true">${R.state.motion?'Ⅱ':'▷'}</span>`}}
function render(){window.REDLINE_MOTION?.stop();window.REDLINE_INTERACTIONS?.stop();R.prefs();const isCase=!!document.body.dataset.project;const p=P.find(v=>v.id===document.body.dataset.project);const home=isCase?R.home:'';
 $('#header').innerHTML=`<div class="header-inner wrap"><a class="brand" href="${home}#home" aria-label="Amin Moniry / ALLin1Wrench"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 40 40" width="32" height="32" fill="none" stroke="currentColor" stroke-width="3" aria-hidden="true"><path d="M20 2v36M2 20h36M7 7l26 26M7 33L33 7"/></svg></span><span>AM<span class="red">.</span></span><small>REDLINE<br>EDITION / 03</small></a><nav class="desktop-nav" aria-label="${e(t('menu'))}">${nav.map(([id,key])=>`<a href="${home}#${id}">${e(t(key))}</a>`).join('')}</nav><div class="header-controls"><button id="search-open" class="search-launch" aria-label="${e(t('search'))}"><span aria-hidden="true">⌘</span><kbd>K</kbd></button><button id="language" class="language-button" aria-label="${R.state.lang==='en'?'تغییر به فارسی':'Switch to English'}">${R.state.lang==='en'?'فا':'EN'}</button><button id="theme" class="icon-button"></button><button id="motion-toggle" class="icon-button"></button><button id="menu-open" class="icon-button mobile-menu" aria-haspopup="dialog" aria-controls="menu-dialog" aria-label="${e(t('menu'))}"><span aria-hidden="true">☰</span></button></div></div>`;
 if(isCase&&!p){$('#main').innerHTML=`<section class="section wrap"><h1>${e(t('pageNotFound'))}</h1><a href="${R.home}">${e(t('back'))}</a></section>`}else $('#main').innerHTML=isCase?window.REDLINE_SECTIONS.caseStudy(p):window.REDLINE_SECTIONS.home();
 $('#footer').innerHTML=`<div class="wrap footer-inner"><span class="mono">AM / ALLin1Wrench</span><p>${e(t('footer'))}</p><div>${R.ext(C.owner.github,'GitHub')}<a href="mailto:${e(C.owner.email)}">Email ↗</a><a href="${home}#home">${e(t('top'))} ↑</a></div><span class="mono">© ${new Date().getFullYear()} ${e(x(C.owner.name))}</span></div>`;
 $('#search-dialog').innerHTML=`<div class="dialog-head"><h2>${e(t('search'))}</h2><button class="icon-button" data-close="search-dialog" aria-label="${e(t('close'))}">×</button></div><label class="sr-only" for="search-input">${e(t('search'))}</label><input id="search-input" type="search" placeholder="${e(t('searchHint'))}" autocomplete="off"><p id="search-status" role="status" class="sr-only"></p><div id="search-results"></div><p class="search-help mono">↑ ↓ / ENTER / ESC</p>`;
 $('#menu-dialog').innerHTML=`<div class="dialog-head"><span class="mono">AM / REDLINE</span><button class="icon-button" data-close="menu-dialog" autofocus aria-label="${e(t('close'))}">×</button></div><nav aria-label="${e(t('menu'))}">${nav.map(([id,key],i)=>`<a href="${home}#${id}"><span class="mono">0${i+1}</span>${e(t(key))}<span aria-hidden="true">↗</span></a>`).join('')}</nav><span class="mono menu-location">${e(x(C.owner.location))}</span>`;
 $('#search-dialog').setAttribute('aria-label',t('search'));$('#menu-dialog').setAttribute('aria-label',t('menu'));$('#image-dialog').setAttribute('aria-label',t('zoom'));$('.skip').textContent=t('skip');controls();
 document.title=isCase&&p?p.title+' — '+x(C.owner.name)+' / REDLINE':x(C.owner.name)+' — ALLin1Wrench / REDLINE';const desc=isCase&&p?x(p.summary):x(C.about.body);$('meta[name="description"]').content=desc;$('meta[property="og:title"]').content=document.title;$('meta[property="og:description"]').content=desc;
 window.REDLINE_INTERACTIONS.init();window.REDLINE_MOTION.init();
}
function language(){const section=$$('main>section[id]').find(s=>{const r=s.getBoundingClientRect();return r.bottom>100&&r.top<innerHeight});const id=section?.id;const offset=section?scrollY-section.offsetTop:scrollY;const details=$$('details[open]').map(d=>$$('details').indexOf(d));const fields=$$('#contact-form input,#contact-form textarea').map(el=>[el.name,el.value]);R.state.lang=R.state.lang==='en'?'fa':'en';render();fields.forEach(([name,value])=>{const el=$('#contact-form')?.elements[name];if(el)el.value=value});details.forEach(i=>{if($$('details')[i])$$('details')[i].open=true});requestAnimationFrame(()=>{const section=id?document.getElementById(id):null;scrollTo({top:section?section.offsetTop+offset:offset,behavior:'instant'});$('#language').focus({preventScroll:true})})}
window.REDLINE_APP={render,language,controls};render();
if(location.hash)requestAnimationFrame(()=>{const id=decodeURIComponent(location.hash.slice(1));document.getElementById(id)?.scrollIntoView({behavior:'instant'})});
})();
