(() => {
'use strict';
const {$,$$,state,t,text:x,esc:e,P}=R;const projects=window.REDLINE_PROJECTS;
const mediaCache=new Map();
let imageObserver=null;
let returnFocus=null,toastTimer,canvasCleanup=()=>{},signalReset=()=>{};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000)}
function openDialog(id,trigger){const d=$('#'+id);if(!d)return;returnFocus=trigger||document.activeElement;d.showModal();document.body.classList.add('dialog-open');if(id==='search-dialog')setTimeout(()=>$('#search-input').focus(),0)}
function closeDialog(d,restore=true){if(!d?.open)return;d.close();document.body.classList.remove('dialog-open');if(restore&&returnFocus?.isConnected)returnFocus.focus({preventScroll:true})}
function system(id){const p=projects.find(v=>v.id===id);if(!p||!$('#system-content'))return;$$('[data-system]').forEach(b=>{const sel=b.dataset.system===id;b.setAttribute('aria-selected',String(sel));b.tabIndex=sel?0:-1});const out=$('#system-content');out.setAttribute('aria-labelledby','system-tab-'+id);out.innerHTML=`<div class="system-title"><h3>${e(p.title)}</h3><span class="mono">${e(t(p.category))}</span></div>${R.pipeline(p,true)}<p>${e(x(p.decision))}</p><div class="system-footer"><span class="form-note">${e(x(R.L('A simplified source-backed flow. No service requests are made here.','جریان ساده‌شده بر پایهٔ کد؛ در اینجا درخواستی به سرویس‌ها ارسال نمی‌شود.')))}</span><a class="text-link" href="${R.caseURL(id)}">${e(t('readCase'))} ↗</a></div>`}
const searchSections=[['home','Home','خانه'],['projects','Selected work','پروژه‌های منتخب'],['about','About Amin','دربارهٔ امین'],['capabilities','Capabilities','توانمندی‌ها'],['systems','System architecture','معماری سیستم'],['process','Approach','روش کار'],['lab','Playground','آزمایشگاه'],['buildlog','Build log','مسیر ساخت'],['notes','Engineering notes','یادداشت‌های مهندسی'],['faq','FAQ','پرسش‌ها'],['contact','Contact','تماس']];
function search(query=''){const items=[...searchSections.map(([id,en,fa])=>({name:x({en,fa}),url:R.home+'#'+id,keys:[en,fa,id].join(' '),label:x(R.L('Section','بخش'))})),...projects.map(p=>({name:p.title,url:R.caseURL(p.id),keys:[p.title,x(p.summary),...p.tags].join(' '),label:t(p.category)}))].filter(v=>v.keys.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));$('#search-results').innerHTML=items.length?items.map(v=>`<a href="${e(v.url)}"><span>${e(v.name)}</span><small>${e(v.label)}</small><span aria-hidden="true">↗</span></a>`).join(''):`<p class="search-empty">${e(t('empty'))}</p>`;$('#search-status').textContent=state.lang==='fa'?`${R.number(items.length)} نتیجه`:`${items.length} results`}
function initSignal(){canvasCleanup();const canvas=$('#signal-canvas');if(!canvas){canvasCleanup=()=>{};return}const ctx=canvas.getContext('2d');if(!ctx)return;let phase=0,playing=false,raf=0,last=0,visible=false;const frequency=$('#frequency');
 const draw=()=>{const width=canvas.clientWidth||400,height=canvas.clientHeight||240;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==width*dpr||canvas.height!==height*dpr){canvas.width=width*dpr;canvas.height=height*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);const css=getComputedStyle(document.documentElement);ctx.clearRect(0,0,width,height);ctx.strokeStyle=css.getPropertyValue('--border').trim();ctx.lineWidth=1;for(let yy=height*.25;yy<=height*.75;yy+=height*.25){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(width,yy);ctx.stroke()}const f=Number(frequency.value);for(let layer=0;layer<3;layer++){ctx.strokeStyle=layer===0?css.getPropertyValue('--accent').trim():css.getPropertyValue('--muted').trim();ctx.globalAlpha=layer===0?1:.23;ctx.lineWidth=layer===0?2.5:1;ctx.beginPath();for(let px=0;px<=width;px+=2){const y=height/2+Math.sin(px/width*Math.PI*2*f+phase+layer*.8)*height*.25*(1-layer*.2);px?ctx.lineTo(px,y):ctx.moveTo(px,y)}ctx.stroke()}ctx.globalAlpha=1;$('#frequency-output').value=R.number(f)};
 const step=time=>{raf=0;if(!playing||document.hidden||!visible)return;phase+=Math.min(time-last||16,40)*.0018;last=time;draw();raf=requestAnimationFrame(step)};
 const sync=()=>{const active=playing&&!document.hidden&&visible;if(active&&!raf){last=performance.now();raf=requestAnimationFrame(step)}else if(!active){cancelAnimationFrame(raf);raf=0}};
 const toggle=()=>{if(!state.motion)return toast(x(R.L('Enable motion in the header to animate.','برای حرکت، انیمیشن را در سربرگ فعال کن.')));playing=!playing;$('#signal-play').setAttribute('aria-pressed',String(playing));$('#signal-play').textContent=t(playing?'pause':'play');sync()};
 const reset=()=>{playing=false;phase=0;frequency.value='3';$('#signal-play').setAttribute('aria-pressed','false');$('#signal-play').textContent=t('play');sync();draw()};signalReset=reset;
 frequency.addEventListener('input',draw);$('#signal-play').addEventListener('click',toggle);$('#signal-reset').addEventListener('click',reset);addEventListener('resize',draw);document.addEventListener('visibilitychange',sync);
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync()},{threshold:.01});observer.observe(canvas);draw();
 canvasCleanup=()=>{cancelAnimationFrame(raf);observer.disconnect();removeEventListener('resize',draw);document.removeEventListener('visibilitychange',sync)};
}
function initMedia(){imageObserver?.disconnect();const load=async im=>{const url=im.dataset.media;if(!url||im.dataset.mediaLoading)return;im.dataset.mediaLoading='true';try{if(!mediaCache.has(url))mediaCache.set(url,fetch(url).then(r=>{if(!r.ok)throw new Error('Media load failed');return r.json()}));const media=await mediaCache.get(url);if(!/^data:image\/webp;base64,[A-Za-z0-9+/=]+$/.test(media.src))throw new Error('Invalid media');im.src=media.src;im.width=Number(media.width)||1600;im.height=Number(media.height)||1000;im.removeAttribute('data-media')}catch{mediaCache.delete(url);im.dispatchEvent(new Event('error'))}};if('IntersectionObserver' in window){imageObserver=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){load(en.target);imageObserver.unobserve(en.target)}}),{rootMargin:'450px'});$$('img[data-media]').forEach(im=>{if(im.dataset.eager==='true')load(im);else imageObserver.observe(im)})}else $$('img[data-media]').forEach(load)}
function init(){system('telebrief');search();initSignal();$('#mirror-input')?.addEventListener('input',()=>{const value=$('#mirror-input').value;$('#mirror-preview').textContent=value||'…';$('#mirror-preview').dir=$('[data-direction][aria-pressed="true"]').dataset.direction;$('#mirror-counter').textContent=R.number([...value].length);$('#mirror-preview').lang=/[\u0600-\u06ff]/.test(value)?'fa':'en'});if($('#mirror-counter'))$('#mirror-counter').textContent=R.number([...$('#mirror-input').value].length);$('#search-input')?.addEventListener('input',ev=>search(ev.target.value));$$('dialog').forEach(d=>{d.oncancel=ev=>{ev.preventDefault();closeDialog(d)};d.onclick=ev=>{if(ev.target===d){const rect=d.getBoundingClientRect();if(ev.clientX<rect.left||ev.clientX>rect.right||ev.clientY<rect.top||ev.clientY>rect.bottom)closeDialog(d)}}});$('#contact-form')?.addEventListener('submit',ev=>{ev.preventDefault();const f=ev.currentTarget;if(!f.checkValidity()||!f.elements.name.value.trim()||!f.elements.message.value.trim()){f.reportValidity();$('#form-status').textContent=t('invalid');return}const name=f.elements.name.value.trim(),email=f.elements.email.value.trim(),message=f.elements.message.value.trim();const subject=(state.lang==='fa'?'گفت‌وگو دربارهٔ پروژه — ':'Project conversation — ')+name;const body=`${message}\n\n${name}\n${email}`;const link='mailto:'+window.REDLINE_CONTENT.owner.email+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);$('#draft-link').href=link;$('#draft-link').hidden=false;$('#form-status').textContent=t('prepared')});$('#contact-form')?.addEventListener('input',()=>{if($('#draft-link')){$('#draft-link').hidden=true;$('#draft-link').removeAttribute('href');$('#form-status').textContent=''}});$$('img').forEach(im=>{const failed=()=>{im.classList.add('image-failed');if(!im.nextElementSibling?.classList.contains('image-error')){const p=document.createElement('p');p.className='image-error';p.textContent=x(R.L('Image unavailable. Project details and source remain accessible.','تصویر در دسترس نیست؛ توضیحات و کد پروژه همچنان قابل‌دسترسی‌اند.'));im.after(p)}};im.addEventListener('error',failed,{once:true});if(im.complete&&!im.naturalWidth)failed()});initMedia()}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button,a');if(!b)return;
 if(b.id==='language')return window.REDLINE_APP.language();
 if(b.id==='theme'){state.theme=state.theme==='dark'?'light':'dark';R.prefs();window.REDLINE_APP.controls();signalReset();return}
 if(b.id==='motion-toggle'){state.motion=!state.motion&&!matchMedia('(prefers-reduced-motion:reduce)').matches;R.storage.set('redline-motion',state.motion?'on':'off');window.REDLINE_MOTION.init();window.REDLINE_APP.controls();signalReset();return}
 if(b.id==='search-open'){search('');$('#search-input').value='';return openDialog('search-dialog',b)}
 if(b.id==='menu-open')return openDialog('menu-dialog',b);
 if(b.dataset.close)return closeDialog($('#'+b.dataset.close));
 if(b.closest('dialog')&&b.tagName==='A')closeDialog(b.closest('dialog'),false);
 if(b.dataset.filter){const key=b.dataset.filter;$$('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));let count=0;$$('.project-card').forEach(el=>{const show=key==='all'||el.dataset.category===key;el.hidden=!show;if(show){count++;el.classList.remove('is-pending')}});$('#project-count').textContent=t('projectCount')+' '+R.number(count)+' '+t('ofFive');return}
 if(b.dataset.system)return system(b.dataset.system);
 if(b.dataset.direction){$$('[data-direction]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));$('#mirror-preview').dir=b.dataset.direction;return}
 if(b.id==='copy-email'){try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(window.REDLINE_CONTENT.owner.email);toast(t('copied'))}catch{toast(t('copyFailed'));const range=document.createRange();range.selectNodeContents($('.email-row a'));const s=getSelection();s.removeAllRanges();s.addRange(range)}return}
 if(b.dataset.image){$('#image-dialog').innerHTML=`<div class="dialog-head"><span>${e(b.dataset.imageTitle||'')}</span><button class="icon-button" data-close="image-dialog" autofocus aria-label="${e(t('close'))}">×</button></div>${R.img(b.dataset.image,b.dataset.imageTitle||'',{eager:true})}`;openDialog('image-dialog',b);initMedia();return}
});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){const d=$$('dialog[open]').at(-1);if(d){ev.preventDefault();closeDialog(d);return}}if((ev.metaKey||ev.ctrlKey)&&ev.key.toLowerCase()==='k'){ev.preventDefault();if($('#search-dialog').open)closeDialog($('#search-dialog'));else{search('');$('#search-input').value='';openDialog('search-dialog')}}
 const tab=ev.target.closest('[data-system]');if(tab&&['ArrowLeft','ArrowRight','Home','End'].includes(ev.key)){ev.preventDefault();const list=$$('[data-system]');let index=list.indexOf(tab);const sign=state.lang==='fa'?-1:1;if(ev.key==='Home')index=0;else if(ev.key==='End')index=list.length-1;else index=(index+(ev.key==='ArrowRight'?sign:-sign)+list.length)%list.length;system(list[index].dataset.system);list[index].focus()}
 if($('#search-dialog')?.open&&['ArrowDown','ArrowUp','Enter'].includes(ev.key)){const list=$$('#search-results a');if(!list.length)return;let index=list.indexOf(document.activeElement);if(ev.key==='Enter'&&document.activeElement===$('#search-input')){ev.preventDefault();list[0].click()}else if(ev.key!=='Enter'){ev.preventDefault();index=ev.key==='ArrowDown'?(index+1)%list.length:(index<=0?list.length-1:index-1);list[index].focus()}}
});
window.REDLINE_INTERACTIONS={init,system,toast,closeDialog,resetSignal:()=>signalReset(),stop:()=>{canvasCleanup();imageObserver?.disconnect()}};
})();
