/* MATRIX visual overlay / no project data or business handlers are replaced. */
(() => {
'use strict';
// Activate only CSS tokens before the unchanged app draws its existing canvases.
document.documentElement.dataset.visual='matrix';
let dispose=[],tweens=[],triggers=[],animations=[],mounted=[],active=false,lenis=null,navBusy=false,decodeTimers=new Set();
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(pointer:fine) and (hover:hover)');
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const text=(en,fa)=>R.state.lang==='fa'?fa:en;
const listen=(node,event,fn,opts)=>{node.addEventListener(event,fn,opts);dispose.push(()=>node.removeEventListener(event,fn,opts))};
const own=node=>{mounted.push(node);return node};
const later=(fn,ms)=>{const id=setTimeout(()=>{decodeTimers.delete(id);fn()},ms);decodeTimers.add(id);return id};
const enabled=()=>R.state.motion&&!reduced.matches;
function timeline(opts={}){const done=opts.onComplete;let t;t=window.gsap?.timeline({...opts,onComplete:()=>{tweens=tweens.filter(v=>v!==t);done?.()}});if(t)tweens.push(t);return t}
function wa(el,keyframes,options){if(!el?.animate)return null;const a=el.animate(keyframes,options);animations.push(a);a.finished.then(()=>{animations=animations.filter(v=>v!==a)},()=>{animations=animations.filter(v=>v!==a)});return a}
function stop(){active=false;navBusy=false;dispose.splice(0).reverse().forEach(f=>{try{f()}catch{}});triggers.splice(0).forEach(t=>t.kill());tweens.splice(0).forEach(t=>t.kill());animations.splice(0).forEach(a=>a.cancel());decodeTimers.forEach(clearTimeout);decodeTimers.clear();lenis?.destroy();lenis=null;mounted.splice(0).forEach(n=>n.remove());$$('.matrix-decoding').forEach(n=>{n.classList.remove('matrix-decoding');n.removeAttribute('data-cipher')});$$('[data-matrix-wait]').forEach(n=>n.removeAttribute('data-matrix-wait'));$$('[data-matrix-styled]').forEach(n=>{n.style.removeProperty('opacity');n.style.removeProperty('transform');n.removeAttribute('data-matrix-styled')});document.documentElement.removeAttribute('data-matrix-engine');}
function mountChrome(){document.documentElement.dataset.visual='matrix';const c=own(document.createElement('canvas'));c.id='matrix-rain';c.setAttribute('aria-hidden','true');c.setAttribute('role','presentation');document.body.prepend(c);const scan=own(document.createElement('div'));scan.className='matrix-scanlines';scan.setAttribute('aria-hidden','true');document.body.prepend(scan);const portal=own(document.createElement('div'));portal.id='matrix-portal';portal.setAttribute('aria-hidden','true');portal.innerHTML='<div class="matrix-portal-ring"></div><div class="matrix-portal-line"></div>';document.body.append(portal);return c}
function initRain(canvas){const ctx=canvas.getContext('2d',{alpha:true});if(!ctx)return;const glyphs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZアイウエオカキクケコ';let width=0,height=0,frame=0,last=0,raf=0,drops=[],atlas,green='#ff718c',light=false;
 const palette=()=>{light=document.documentElement.dataset.theme==='light';green=light?'#b71940':'#ff718c'};
 const size=()=>{palette();width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5,Math.sqrt(2000000/(width*height)));canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);atlas=document.createElement('canvas');atlas.width=glyphs.length*24;atlas.height=64;const ac=atlas.getContext('2d');ac.font='16px monospace';ac.fillStyle=green;ac.textBaseline='top';[0,32].forEach((y,i)=>{ac.globalAlpha=i?1:.35;[...glyphs].forEach((g,n)=>ac.fillText(g,n*24,y))});drops=Array.from({length:Math.ceil(width/24)},(_,i)=>({x:i*24,y:Math.random()*height,speed:35+Math.random()*100,layer:i%3,seed:Math.random()*glyphs.length}));staticFrame()};
 const staticFrame=()=>{ctx.clearRect(0,0,width,height);ctx.globalAlpha=light?.13:.16;drops.forEach((d,i)=>{for(let j=0;j<5;j++){const g=(i*7+j*3)%glyphs.length;ctx.drawImage(atlas,g*24,0,24,24,d.x,(d.y+j*30)%height,18,18)}});ctx.globalAlpha=1};
 const draw=(dt)=>{ctx.globalCompositeOperation='destination-out';ctx.globalAlpha=.08;ctx.fillRect(0,0,width,height);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';for(const d of drops){d.y+=d.speed*dt; if(d.y>height+80)d.y=-Math.random()*200;const g=(Math.floor(d.seed)+Math.floor(frame/7))%glyphs.length;ctx.globalAlpha=(light?.22:.4)*(d.layer===0?.5:1);const sz=d.layer===0?11:d.layer===1?15:18;ctx.drawImage(atlas,g*24,d.layer===2?32:0,24,24,d.x,d.y,sz,sz)}ctx.globalAlpha=1;frame++};
 const step=now=>{raf=0;if(!active||document.hidden||!enabled()||$('dialog[open]'))return;const interval=fine.matches?16:33;if(now-last>=interval){draw(Math.min((now-last)/1000||.016,.06));last=now}raf=requestAnimationFrame(step)};
 const sync=()=>{cancelAnimationFrame(raf);raf=0;last=performance.now();if(active&&!document.hidden&&enabled()&&!$('dialog[open]'))raf=requestAnimationFrame(step);else if(!enabled())staticFrame()};
 let resize=0;listen(window,'resize',()=>{clearTimeout(resize);resize=setTimeout(()=>{size();sync()},150)},{passive:true});listen(document,'visibilitychange',sync);const ob=new MutationObserver(()=>{size();sync()});ob.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});const dialogs=new MutationObserver(sync);$$('dialog').forEach(d=>dialogs.observe(d,{attributes:true,attributeFilter:['open']}));size();sync();dispose.push(()=>{cancelAnimationFrame(raf);clearTimeout(resize);ob.disconnect();dialogs.disconnect()});
}
function mountCinematic(){const hero=$('#home.hero');if(!hero)return;const panel=own(document.createElement('div'));panel.className='matrix-cinema';panel.innerHTML=`<div class="matrix-cinema-copy"><span class="mono matrix-label">VISUAL LAYER / MATRIX</span><h2>${R.esc(text('Enter the signal.','وارد جریان شو.'))}</h2><p>${R.esc(text('Same work. A different dimension.','همان پروژه‌ها؛ در بُعدی متفاوت.'))}</p><div class="matrix-cinema-actions"><a class="button primary" href="#projects">${R.esc(text('Enter the work','ورود به پروژه‌ها'))} <span aria-hidden="true">↗</span></a><a class="text-link" href="#about">${R.esc(text('Skip the introduction','ردکردن معرفی'))}</a></div></div><div class="matrix-core" aria-hidden="true"><div class="matrix-core-ring"></div><div class="matrix-core-ring matrix-core-ring-two"></div><div class="matrix-core-orbit"></div><span>AM / 03</span></div><div class="matrix-cinema-stats"><span><b class="matrix-counter" data-end="${$$('.project-card').length}" aria-hidden="true">${$$('.project-card').length}</b> ${R.esc(text('featured projects','پروژهٔ منتخب'))}</span><span><b class="matrix-counter" data-end="${$$('main>section').length}" aria-hidden="true">${$$('main>section').length}</b> ${R.esc(text('existing sections','بخش موجود'))}</span><span>${R.esc(text('No gate. Scroll freely.','بدون مانع؛ آزادانه اسکرول کن.'))}</span></div>`;$('.hero-topline',hero).after(panel);
 if(enabled()&&window.gsap){timeline().fromTo($('.matrix-core',panel),{opacity:0,scale:.75,rotation:-25},{opacity:1,scale:1,rotation:0,duration:1.25,ease:'expo.out'},0).fromTo($$('.matrix-cinema-copy>*',panel),{opacity:0,y:22},{opacity:1,y:0,duration:.8,stagger:.12,ease:'power3.out'},.12);$$('.matrix-cinema-copy>*',panel).forEach(n=>n.dataset.matrixStyled='1');$$('.matrix-counter',panel).forEach(el=>{const end=+el.dataset.end,obj={n:0};timeline().to(obj,{n:end,duration:1.1,ease:'power2.out',onUpdate:()=>{el.textContent=R.number(Math.round(obj.n))}})});timeline({repeat:-1}).to($('.matrix-core-orbit',panel),{rotation:360,duration:18,ease:'none'})}
}
function decodeText(el){if(!el||!enabled()||el.classList.contains('matrix-decoding')||!el.textContent.trim())return;const original=el.innerText;const chars=Array.from(original);const pool=R.state.lang==='fa'?'۰۱۲۳۴۵۶۷۸۹':'0123456789ABCDEF';let step=0;el.classList.add('matrix-decoding');const tick=()=>{if(!active||!el.isConnected||!enabled()){el.classList.remove('matrix-decoding');el.removeAttribute('data-cipher');return}const count=Math.ceil(chars.length*(step/8));el.dataset.cipher=chars.map((c,i)=>/\s|[.,؛،؟!×+]/.test(c)||i<count?c:pool[Math.floor(Math.random()*pool.length)]).join('');step++;if(step<=8)later(tick,70);else{el.classList.remove('matrix-decoding');el.removeAttribute('data-cipher')}};tick()}
function revealChildren(el){if(!enabled()||el.hidden)return;const children=$$(':scope > .project-card-info,:scope > .project-visual,:scope > h2,:scope > h3,:scope > p,:scope > li,:scope > .flow-node,:scope > .tags,:scope > .text-link,:scope > blockquote',el);if(!children.length)return;children.forEach(n=>n.dataset.matrixStyled='1');if(window.gsap)timeline().fromTo(children,{opacity:0,y:26,scale:.975},{opacity:1,y:0,scale:1,duration:.7,stagger:.08,ease:'power3.out',clearProps:'opacity,transform'});else children.forEach((n,i)=>wa(n,[{opacity:0,transform:'translateY(26px) scale(.975)'},{opacity:1,transform:'none'}],{duration:650,delay:i*70,easing:'cubic-bezier(.22,1,.36,1)'}))}
function initStaggers(){if(!('IntersectionObserver' in window))return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){revealChildren(e.target);const heading=$('h2,h3',e.target)||e.target;if(heading.matches('h2,h3'))decodeText(heading);io.unobserve(e.target)}}),{threshold:.1});$$('.project-card,.capability-card,.lab-card,.case-block,.section-heading,.about-layout,.archive-row,.note-card,.build-entry,.timeline-item,.process-list li,.identity-grid>div,.faq-item,.contact-layout').forEach(n=>io.observe(n));dispose.push(()=>io.disconnect());const system=$('#system-content');if(system){const mo=new MutationObserver(()=>{revealChildren(system);decodeText($('.system-title h3',system))});mo.observe(system,{childList:true});dispose.push(()=>mo.disconnect())}}
function mountStory(){const process=$('#process');if(!process)return;process.classList.add('matrix-story');const panel=own(document.createElement('div'));panel.className='matrix-story-deck';panel.setAttribute('aria-hidden','true');panel.innerHTML='<div class="matrix-story-rail"><i></i></div>'+$$('.process-list li',process).map((el,i)=>`<div class="matrix-story-step"><span class="mono">0${i+1}</span><strong>${R.esc($('h3',el).textContent)}</strong></div>`).join('');$('.process-list',process).before(panel);if(!enabled())return;const steps=$$('.process-list li',process);if(window.ScrollTrigger&&window.gsap){steps.forEach((el,i)=>{triggers.push(ScrollTrigger.create({trigger:el,start:'top 78%',end:'bottom 22%',onEnter:()=>activate(i),onEnterBack:()=>activate(i)}))});if(!CSS.supports('animation-timeline: view()')){const t=timeline({scrollTrigger:{trigger:process,start:'top bottom',end:'bottom top',scrub:.4}}).fromTo($('.matrix-story-rail i',panel),{scaleX:0},{scaleX:1,ease:'none'});if(t.scrollTrigger)triggers.push(t.scrollTrigger)}}else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)activate(steps.indexOf(e.target))}),{threshold:.3});steps.forEach(s=>io.observe(s));dispose.push(()=>io.disconnect())}
 function activate(i){$$('.matrix-story-step',panel).forEach((s,n)=>s.classList.toggle('is-active',i===n));wa($$('.matrix-story-step',panel)[i],[{transform:'translateY(9px)',opacity:.55},{transform:'none',opacity:1}],{duration:450,easing:'ease-out'})}
}
function mountField(){const lab=$('#lab');if(!lab)return;const field=own(document.createElement('div'));field.className='matrix-field-panel';field.innerHTML=`<div class="matrix-field-head"><div><span class="mono matrix-label">VISUAL FIELD / LOCAL ONLY</span><h3>${R.esc(text('Bend the signal.','جریان را خم کن.'))}</h3></div><button type="button" class="small-button matrix-field-reset">${R.esc(text('Reset field','بازنشانی میدان'))}</button></div><div class="matrix-field" tabindex="0" role="img" aria-label="${R.esc(text('Interactive decorative field. Move your pointer or use the arrow keys.','میدان تزئینی تعاملی؛ اشاره‌گر را حرکت بده یا از کلیدهای جهت استفاده کن.'))}"><div class="matrix-field-grid" aria-hidden="true"></div><div class="matrix-field-glow" aria-hidden="true"></div><div class="matrix-field-target" aria-hidden="true"><i></i><span>+</span></div><span class="matrix-field-coordinate mono" aria-hidden="true">X / 0 &nbsp; Y / 0</span></div><p class="form-note">${R.esc(text('A visual-only addition. Pointer or arrow keys · no network requests. The two original experiments remain below.','افزوده‌ای صرفاً بصری؛ اشاره‌گر یا کلیدهای جهت، بدون درخواست شبکه. دو آزمایش اصلی در ادامه حفظ شده‌اند.'))}</p>`;$('.lab-grid',lab).before(field);const box=$('.matrix-field',field),glow=$('.matrix-field-glow',field),target=$('.matrix-field-target',field),coordinate=$('.matrix-field-coordinate',field);let frame=0,x=.5,y=.5;
 const draw=()=>{frame=0;glow.style.transform=`translate(${(x-.5)*200}px,${(y-.5)*110}px)`;target.style.transform=`translate(${(x-.5)*box.clientWidth*.64}px,${(y-.5)*box.clientHeight*.58}px)`;coordinate.textContent=`X / ${Math.round((x-.5)*100)}   Y / ${Math.round((y-.5)*100)}`};const request=()=>{if(!frame)frame=requestAnimationFrame(draw)};
 listen(box,'pointermove',ev=>{if(!enabled()||!fine.matches)return;const rect=box.getBoundingClientRect();x=Math.max(0,Math.min(1,(ev.clientX-rect.left)/rect.width));y=Math.max(0,Math.min(1,(ev.clientY-rect.top)/rect.height));request()},{passive:true});listen(box,'keydown',ev=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key))return;ev.preventDefault();if(!enabled())return;if(ev.key==='ArrowLeft')x=Math.max(0,x-.08);if(ev.key==='ArrowRight')x=Math.min(1,x+.08);if(ev.key==='ArrowUp')y=Math.max(0,y-.08);if(ev.key==='ArrowDown')y=Math.min(1,y+.08);request()});listen($('.matrix-field-reset',field),'click',()=>{x=y=.5;request()});dispose.push(()=>cancelAnimationFrame(frame));draw();
}
function portal(){const el=$('#matrix-portal');if(!enabled()||!el)return;animations.filter(a=>a.effect?.target===el).forEach(a=>a.cancel());wa(el,[{opacity:0,transform:'scale(.82)'},{opacity:.6,offset:.35,transform:'scale(1)'},{opacity:0,transform:'scale(1.3)'}],{duration:650,easing:'cubic-bezier(.22,1,.36,1)'})}
function initNavigation(){listen(document,'click',ev=>{const a=ev.target.closest('a[href]');if(!a||ev.defaultPrevented||ev.button!==0||ev.metaKey||ev.ctrlKey||ev.shiftKey||ev.altKey||a.target==='_blank'||a.hasAttribute('download'))return;let url;try{url=new URL(a.href)}catch{return}if(url.origin!==location.origin)return;const current=url.pathname===location.pathname&&url.search===location.search;if(!current||!url.hash||!enabled())return;const id=decodeURIComponent(url.hash.slice(1));const section=document.getElementById(id);if(!section||a.closest('dialog')||navBusy)return;ev.preventDefault();navBusy=true;portal();const update=()=>{if(location.hash!==url.hash)history.pushState(null,'',url.hash);(lenis?lenis.scrollTo(section,{immediate:true}):section.scrollIntoView({behavior:'instant',block:'start'}));};const reveal=()=>{revealChildren(section);decodeText($('h2',section));navBusy=false};if(document.startViewTransition){try{const vt=document.startViewTransition(update);vt.finished.then(reveal,reveal);dispose.push(()=>vt.skipTransition())}catch{update();reveal()}}else{update();wa(section,[{opacity:.3,transform:'translateY(28px) scale(.985)'},{opacity:1,transform:'none'}],{duration:600,easing:'cubic-bezier(.22,1,.36,1)'});later(reveal,100)}});
 listen(document,'click',ev=>{const b=ev.target.closest('button');if(!b||!enabled())return;if(b.dataset.system){const from=b.getBoundingClientRect();const ghost=own(document.createElement('div'));ghost.className='matrix-shared-ghost';ghost.setAttribute('aria-hidden','true');ghost.textContent=b.textContent;document.body.append(ghost);ghost.style.cssText=`left:${from.left}px;top:${from.top}px;width:${from.width}px;height:${from.height}px`;requestAnimationFrame(()=>{if(!ghost.isConnected)return;const to=$('#system-content .system-title h3')?.getBoundingClientRect();if(!to){ghost.remove();return}const a=wa(ghost,[{opacity:.75,transform:'none'},{opacity:0,transform:`translate(${to.left-from.left}px,${to.top-from.top}px) scale(.75)`}],{duration:550,easing:'cubic-bezier(.22,1,.36,1)'});a?.finished.then(()=>ghost.remove(),()=>ghost.remove())})}else if(!b.dataset.close){wa(b,[{transform:'scale(1)'},{transform:'scale(.96)',offset:.4},{transform:'scale(1)'}],{duration:210,easing:'ease-out'})}},true);
}
function initDialogs(){const obs=new MutationObserver(es=>es.forEach(e=>{const d=e.target;if(d.open){lenis?.stop();if(enabled())wa(d,[{opacity:0,transform:'translateY(22px) scale(.96)'},{opacity:1,transform:'none'}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'})}else if(!$('dialog[open]'))lenis?.start()}));$$('dialog').forEach(d=>obs.observe(d,{attributes:true,attributeFilter:['open']}));dispose.push(()=>obs.disconnect())}
function initMediaScans(){$$('img[data-media]').forEach(im=>{const cover=im.closest('.project-image,.object-art,.case-cover')||im.parentElement;if(!cover)return;cover.dataset.matrixWait='1';const done=()=>cover.removeAttribute('data-matrix-wait');listen(im,'load',done);listen(im,'error',done)});const mo=new MutationObserver(()=>$$('[data-matrix-wait]').forEach(el=>{const im=$('img',el);if(im?.complete&&im.naturalWidth>1&&!im.dataset.media)el.removeAttribute('data-matrix-wait')}));mo.observe(document.body,{attributes:true,subtree:true,attributeFilter:['src','data-media']});dispose.push(()=>mo.disconnect())}
function initGlitch(){$$('.hero .title-line>span').forEach(el=>{el.dataset.matrixLabel=el.textContent;dispose.push(()=>el.removeAttribute('data-matrix-label'))})}
function initMagnetic(){if(!enabled()||!fine.matches)return;$$('.project-visual,.capability-card').forEach(el=>{let raf=0;const reset=()=>{cancelAnimationFrame(raf);el.style.removeProperty('transform')};listen(el,'pointermove',ev=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const r=el.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width-.5,y=(ev.clientY-r.top)/r.height-.5;el.dataset.matrixStyled='1';el.style.transform=`perspective(1000px) rotateX(${-y*2}deg) rotateY(${x*2}deg) translateY(-3px)`})},{passive:true});listen(el,'pointerleave',reset);dispose.push(reset)})}
function initSmoothScroll(){if(!enabled()||!fine.matches||!window.Lenis)return;lenis=new Lenis({lerp:.115,smoothWheel:true,syncTouch:false,anchors:false});const tick=time=>{if(!document.hidden)lenis?.raf(time*1000)};if(window.gsap){gsap.ticker.add(tick);dispose.push(()=>gsap.ticker.remove(tick));}else{let frame=0;const loop=time=>{lenis?.raf(time);if(active)frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);dispose.push(()=>cancelAnimationFrame(frame))}if(window.ScrollTrigger)lenis.on('scroll',ScrollTrigger.update);document.documentElement.dataset.matrixEngine='gsap-scrolltrigger-lenis'}

function initSignaturePaths(){if(!enabled())return;
 const ns='http://www.w3.org/2000/svg';
 $$('.project-visual,.lab-card,.capability-card,.case-cover').forEach(el=>{const svg=own(document.createElementNS(ns,'svg'));svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.classList.add('matrix-trace-frame');const path=document.createElementNS(ns,'path');path.setAttribute('d','M2 2H98V98H2Z');path.setAttribute('pathLength','400');svg.append(path);el.append(svg);const io=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){io.unobserve(el);if(window.gsap)timeline().fromTo(path,{strokeDashoffset:400},{strokeDashoffset:0,duration:1.7,ease:'power2.out'});else wa(path,[{opacity:0},{opacity:1}],{duration:1000})}}),{threshold:.08});io.observe(el);dispose.push(()=>io.disconnect())});
 $$('.section-label').forEach(el=>{const star=own(document.createElement('span'));star.className='matrix-legacy-star';star.setAttribute('aria-hidden','true');star.innerHTML='<svg viewBox="0 0 40 40" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 2v36M2 20h36M7 7l26 26M7 33L33 7"/></svg>';el.append(star)});
 const io=new IntersectionObserver(es=>es.forEach(en=>{if(!en.isIntersecting)return;io.unobserve(en.target);const children=$$(':scope>h3,:scope>p,:scope>span,:scope>h2',en.target);if(!children.length)return;children.forEach(n=>n.dataset.matrixStyled='1');if(window.gsap)timeline().fromTo(children,{opacity:0,x:R.state.lang==='fa'?22:-22,y:12},{opacity:1,x:0,y:0,duration:.85,stagger:.1,ease:'power3.out',clearProps:'transform,opacity'});else children.forEach(n=>wa(n,[{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'none'}],{duration:800}))}),{threshold:.08});$$('.feature-list li').forEach(el=>io.observe(el));dispose.push(()=>io.disconnect())
}
function initChapterDial(){const sections=$$('main>section[id]');if(!sections.length||!fine.matches)return;let index=0;const nav=own(document.createElement('nav'));nav.className='matrix-chapter-dial';nav.setAttribute('aria-label',text('Section journey','مسیر بخش‌ها'));nav.innerHTML='<div class="matrix-dial-orbit" aria-hidden="true"></div><span class="matrix-dial-count mono" aria-hidden="true"></span><span class="matrix-dial-name"></span><div><a class="matrix-dial-prev" aria-label="'+R.esc(text('Previous section','بخش قبلی'))+'">↑</a><a class="matrix-dial-next" aria-label="'+R.esc(text('Next section','بخش بعدی'))+'">↓</a></div>';document.body.append(nav);
 const update=i=>{index=i;$('.matrix-dial-count',nav).textContent=String(i+1).padStart(2,'0')+' / '+sections.length;const label=$('.section-label>span:nth-child(2)',sections[i]);$('.matrix-dial-name',nav).textContent=label?.textContent||text('Introduction','معرفی');[['.matrix-dial-prev',i-1],['.matrix-dial-next',i+1]].forEach(([s,n])=>{const a=$(s,nav);if(sections[n]){a.href='#'+sections[n].id;a.removeAttribute('aria-disabled');a.tabIndex=0}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');a.tabIndex=-1}});if(enabled())wa($('.matrix-dial-orbit',nav),[{transform:'rotate(0deg)'},{transform:'rotate(180deg)'}],{duration:900,easing:'cubic-bezier(.22,1,.36,1)'})};const io=new IntersectionObserver(es=>{for(const e of es)if(e.isIntersecting)update(sections.indexOf(e.target))},{rootMargin:'-20% 0px -55% 0px'});sections.forEach(s=>io.observe(s));dispose.push(()=>io.disconnect());update(index)
}
function mountLegacyFooter(){const footer=$('#footer');if(!footer)return;footer.classList.add('has-legacy-footer');dispose.push(()=>footer.classList.remove('has-legacy-footer'));const box=own(document.createElement('div'));box.className='matrix-legacy-footer';box.innerHTML='<div class="matrix-legacy-border" aria-hidden="true"></div><span class="matrix-legacy-watermark" aria-hidden="true">A1W</span><h2 class="matrix-legacy-title" dir="ltr" aria-label="ALLin1Wrench"><span aria-hidden="true"></span></h2><img class="matrix-legacy-logo" src="'+location.origin+'/pics/Logo.webp" width="72" height="72" alt="ALLin1Wrench logo" loading="lazy"><p class="matrix-legacy-rights" dir="ltr">© '+new Date().getFullYear()+' ALLin1Wrench by Amin Moniry<br>All Rights Reserved</p>';footer.append(box);const title=$('.matrix-legacy-title>span',box),full='ALLin1Wrench',white=[1,2,6];let visible=false,count=0,direction=1,timer=null;
 const paint=()=>{title.replaceChildren();[...full].slice(0,count).forEach((ch,i)=>{const span=document.createElement('span');span.textContent=ch;span.className=white.includes(i)?'legacy-white':'legacy-red';title.append(span)})};
 const tick=()=>{timer=null;if(!active||!visible||document.hidden||!enabled())return;count+=direction;paint();let wait=direction===1?150:100;if(count===full.length){direction=-1;wait=2000}else if(count===0){direction=1;wait=500}timer=setTimeout(tick,wait)};
 const sync=()=>{clearTimeout(timer);timer=null;if(!enabled()){count=full.length;paint();return}if(visible&&!document.hidden)timer=setTimeout(tick,150)};
 const io=new IntersectionObserver(es=>{visible=es[0].isIntersecting;sync()},{threshold:.03});io.observe(box);listen(document,'visibilitychange',sync);dispose.push(()=>{io.disconnect();clearTimeout(timer)});if(!enabled()){count=full.length;paint()}else{count=0;paint()}
}

function init(){stop();active=true;if(window.gsap&&window.ScrollTrigger)gsap.registerPlugin(ScrollTrigger);initRain(mountChrome());mountCinematic();mountStory();mountField();initStaggers();initNavigation();initDialogs();initMediaScans();initGlitch();initMagnetic();initSignaturePaths();initChapterDial();mountLegacyFooter();initSmoothScroll();if(window.ScrollTrigger)later(()=>ScrollTrigger.refresh(),80)}
function clearShared(){$$('[data-matrix-shared]').forEach(n=>{n.style.removeProperty('view-transition-name');n.removeAttribute('data-matrix-shared')})}
function sharedFor(url){clearShared();if(!enabled())return;const match=url.pathname.match(/\/work\/([\w-]+)\.html$/);const id=match?.[1]||document.body.dataset.project;if(!id)return;let title,cover;if(document.body.dataset.project===id){title=$('.case-hero h1');cover=$('.case-cover')}else{const link=$$('.project-card h3 a').find(a=>new URL(a.href).pathname.endsWith('/work/'+id+'.html'));title=link?.closest('h3');cover=link?.closest('.project-card')?.querySelector('.project-visual')}[[title,'matrix-project-title'],[cover,'matrix-project-cover']].forEach(([n,name])=>{if(n){n.dataset.matrixShared='1';n.style.viewTransitionName=name}})}
// Cross-document listeners must exist before the first application render.
addEventListener('pageswap',ev=>{if(ev.viewTransition&&ev.activation){sharedFor(new URL(ev.activation.entry.url));ev.viewTransition.finished.finally(clearShared).catch(()=>{})}});
addEventListener('pagereveal',ev=>{if(ev.viewTransition){sharedFor(new URL(location.href));ev.viewTransition.finished.finally(clearShared).catch(()=>{})}});
window.MATRIX_FX={init,stop,portal,decodeText,sharedFor,getDiagnostics:()=>({active,gsap:!!window.gsap,scrollTrigger:!!window.ScrollTrigger,lenis:!!lenis,reduced:reduced.matches,viewTransitions:!!document.startViewTransition,scrollTimeline:CSS.supports('animation-timeline: view()'),ownedNodes:mounted.filter(n=>n.isConnected).length,ownedTriggers:triggers.length})};
})();
